//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LyraConvolutionWizards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WizardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WizardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LyraConvolutionWizards.Properties.WizardResources", typeof(WizardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lyra {
            get {
                object obj = ResourceManager.GetObject("Lyra", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Bcl_AsyncInterfaces {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Bcl_AsyncInterfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Microsoft.Bcl.AsyncInterfaces&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1&quot;&gt;
        ///            &lt;summary&gt;Provides the core logic for implementing a manual-reset &lt;see cref=&quot;T:System.Threading.Tasks.Sources.IValueTaskSource&quot;/&gt; or &lt;see cref=&quot;T:System.Threading.Tasks.Sources.IValueTaskSource`1&quot;/&gt;.&lt;/summary&gt;
        ///            &lt;typeparam name=&quot;TResult&quot;&gt;&lt;/typeparam&gt;
        ///        &lt;/member&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_Bcl_AsyncInterfaces1 {
            get {
                return ResourceManager.GetString("Microsoft_Bcl_AsyncInterfaces1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Deployment_Compression {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Deployment_Compression", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Deployment_Compression_Cab {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Deployment_Compression_Cab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pakchunk0_Windows {
            get {
                object obj = ResourceManager.GetObject("pakchunk0_Windows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pakchunk0_Windows1 {
            get {
                object obj = ResourceManager.GetObject("pakchunk0_Windows1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pakchunk0_Windows2 {
            get {
                object obj = ResourceManager.GetObject("pakchunk0_Windows2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Buffers {
            get {
                object obj = ResourceManager.GetObject("System_Buffers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Buffers&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Buffers.ArrayPool`1&quot;&gt;
        ///      &lt;summary&gt;Provides a resource pool that enables reusing instances of type &lt;see cref=&quot;T[]&quot;&gt;&lt;/see&gt;.&lt;/summary&gt;
        ///      &lt;typeparam name=&quot;T&quot;&gt;The type of the objects that are in the resource pool.&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Buffers.ArrayPool`1.#ctor&quot;&gt;
        ///      &lt;summary&gt;Initializes a new instance of the &lt;see cref=&quot;T:S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Buffers1 {
            get {
                return ResourceManager.GetString("System_Buffers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Memory {
            get {
                object obj = ResourceManager.GetObject("System_Memory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Memory&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Span`1&quot;&gt;
        ///      &lt;typeparam name=&quot;T&quot;&gt;&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(`0[])&quot;&gt;
        ///      &lt;param name=&quot;array&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(System.Void*,System.Int32)&quot;&gt;
        ///      &lt;param name=&quot;pointer&quot;&gt;&lt;/param&gt;
        ///      &lt;param name=&quot;length&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Memory1 {
            get {
                return ResourceManager.GetString("System_Memory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Numerics_Vectors {
            get {
                object obj = ResourceManager.GetObject("System_Numerics_Vectors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Numerics.Vectors&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Numerics.Matrix3x2&quot;&gt;
        ///      &lt;summary&gt;Represents a 3x2 matrix.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Numerics.Matrix3x2.#ctor(System.Single,System.Single,System.Single,System.Single,System.Single,System.Single)&quot;&gt;
        ///      &lt;summary&gt;Creates a 3x2 matrix from the specified components.&lt;/summary&gt;
        ///      &lt;param name=&quot;m11&quot;&gt;The value to assign to the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Numerics_Vectors1 {
            get {
                return ResourceManager.GetString("System_Numerics_Vectors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Runtime_CompilerServices_Unsafe {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_CompilerServices_Unsafe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Runtime.CompilerServices.Unsafe&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Runtime.CompilerServices.Unsafe&quot;&gt;
        ///      &lt;summary&gt;Contains generic, low-level functionality for manipulating pointers.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Runtime.CompilerServices.Unsafe.Add``1(``0@,System.Int32)&quot;&gt;
        ///      &lt;summary&gt;Adds an element offset to the given reference.&lt;/summary&gt;
        ///      &lt;param name=&quot;source&quot;&gt;The re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Runtime_CompilerServices_Unsafe1 {
            get {
                return ResourceManager.GetString("System_Runtime_CompilerServices_Unsafe1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Encodings_Web {
            get {
                object obj = ResourceManager.GetObject("System_Text_Encodings_Web", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Text.Encodings.Web&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Text.Encodings.Web.HtmlEncoder&quot;&gt;
        ///      &lt;summary&gt;Represents an HTML character encoding.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Text.Encodings.Web.HtmlEncoder.#ctor&quot;&gt;
        ///      &lt;summary&gt;Initializes a new instance of the &lt;see cref=&quot;T:System.Text.Encodings.Web.HtmlEncoder&quot; /&gt; class.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Text.En [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Text_Encodings_Web1 {
            get {
                return ResourceManager.GetString("System_Text_Encodings_Web1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Text_Json {
            get {
                object obj = ResourceManager.GetObject("System_Text_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;System.Text.Json&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;P:System.HexConverter.CharToHexLookup&quot;&gt;
        ///            &lt;summary&gt;Map from an ASCII char to its hex value, e.g. arr[&apos;b&apos;] == 11. 0xFF means it&apos;s not a hex digit.&lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;T:System.Text.Json.JsonNamingPolicy&quot;&gt;
        ///            &lt;summary&gt;
        ///            Determines the naming policy used to convert a string-based name to another format, such a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Text_Json1 {
            get {
                return ResourceManager.GetString("System_Text_Json1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Threading_Tasks_Extensions {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Tasks_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Threading.Tasks.Extensions&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Runtime.CompilerServices.ValueTaskAwaiter`1&quot;&gt;
        ///      &lt;typeparam name=&quot;TResult&quot;&gt;&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult&quot;&gt;
        ///      &lt;returns&gt;&lt;/returns&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;P:System.Runtime.CompilerServices.ValueTaskAwaiter`1.IsCompleted&quot;&gt;
        ///      &lt;returns&gt;&lt;/returns&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Threading_Tasks_Extensions1 {
            get {
                return ResourceManager.GetString("System_Threading_Tasks_Extensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_ValueTuple {
            get {
                object obj = ResourceManager.GetObject("System_ValueTuple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;System.ValueTuple&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///    &lt;/members&gt;
        ///&lt;/doc&gt;
        ///.
        /// </summary>
        internal static string System_ValueTuple1 {
            get {
                return ResourceManager.GetString("System_ValueTuple1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] uninstall {
            get {
                object obj = ResourceManager.GetObject("uninstall", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
